name = "minimal-bulma"
license = "MIT"
licenselink = "https://github.com/deadlysyn/minimal-bulma/blob/master/LICENSE.md"
description = "Personal blog theme powered by Hugo"
homepage = "http://github.com/deadlysyn/minimal-bulma"
tags = ["blog", "minimal", "personal", "responsive"]
features = ["responsive"]
min_version = "0.24.1"

[author]
  name = "Mike Hoskins"
  homepage = "https://deadlysyn.com"

[original]
  author = "Calin Tataru"
  homepage = "https://calintat.github.io"
  repo = "https://github.com/calintat/minimal"
