baseURL = "http://example.com/"
languageCode = "en-us"
title = "Minimal"
theme = "minimal"

[params]
    author = "Mike Hoskins"
    description = "Personal blog theme powered by Hugo"
    githubUsername = "#"
    accent = "#fe8019"
    backgroundColor = "#ffffff"
    font = "Source Code Pro" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "base16/gruvbox-dark-medium"
    # support common languages if not specified...
    # highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "fa-solid fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username"
    name = "fa-brands fa-github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/username"
    name = "fa-brands fa-linkedin"
    weight = 3
